### ISSUE TITLE
爬到的数据并不是按顺序展示的

### ISSUE THREAD

**Issue by sunchenguang** [chokcoco/cnblogSpider#2]
爬到的数据并不是按顺序展示的，async一次并发5个请求，这5个请求返回的时间可能是随机的，有没有办法按顺序来

**Comment by chokcoco** [comment]
对，因为回调的时间是不确定，可以爬文章发布时间，把数据接收完了再排序。

**Comment by sunchenguang** [comment]
奥奥，回调，异步这些原理还不是太懂
